version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=cadastro"
    container_name: postgres
    networks:
      - api-backend
    ports:
      - "5432:5432"

  api:
    container_name: java-register-api
    build: .
    ports:
      - "9000:9000"
    restart: always
    depends_on:
      - db
    networks:
      - api-backend

networks:
  api-backend:
    driver: "bridge"
